[package]
name = "hello-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
wasmtime = { version = "17.0.0", features = ["component-model"] }
wasmtime-wasi = "17.0.0"
